/* This file was automatically generated by µCurve (ucurve).
 * DO NOT EDIT MANUALLY, WILL BE OVERWRITTEN.
 * Creation: ${today}
 */

#ifndef __${lup_name.upper()}_H__
#define __${lup_name.upper()}_H__

#include <stdint.h>

${out_type} ${lup_name}(${in_type} value);

#endif
