/* This file was automatically generated by µCurve (ucurve).
 * DO NOT EDIT MANUALLY, WILL BE OVERWRITTEN.
 * Creation: ${today}
 */

#include <stdint.h>
%if struct_lookup == "avr-progmem":
#include <avr/pgmspace.h>
%endif
#include "${filename}.h"

struct lookup_entry_t {
	${in_type} x;
	${out_type} y;
};

/* Maximum error: (y_true - y_interpolated) = ${"%+.2f" % (max_error)} ${out_yname} */
%if struct_lookup == "avr-progmem":
static const struct lookup_entry_t PROGMEM lookup_table[] = {
%else:
static const struct lookup_entry_t lookup_table[] = {
%endif
	%for point in points:
	%if point.error is not None:
	{ .x = ${point.x}, .y = ${point.y} },		/* ${"%+.1f" % (point.error)} ${out_yname} */
	%else:
	{ .x = ${point.x}, .y = ${point.y} },
	%endif
	%endfor
};

static struct lookup_entry_t get_lookup_entry(${idx_type} index) {
%if struct_lookup == "avr-progmem":
	struct lookup_entry_t entry;
	memcpy_P(&entry, lookup_table + index, sizeof(struct lookup_entry_t));
	return entry;
%else:
	return lookup_table[index];
%endif
}

static ${out_type} interpolate(${in_type} xvalue, const struct lookup_entry_t *low, const struct lookup_entry_t *high) {
	${in_type} xspan = high->x - low->x;
	${yspan_type} yspan = high->y - low->y;
	${in_type} xwindow = xvalue - low->x;

	/* slope = yspan / xspan = (high->y - low->y) / (high->x - low->x)
	   return low->y + (xwindow / xspan) * yspan
	   i.e., return low->y + xwindow / xspan * yspan
	*/
	return low->y + (${win_mul_yspan_type})xwindow * yspan / (${win_mul_yspan_type})xspan;
}

${out_type} ${lup_name}(${in_type} xvalue) {
	if (xvalue < ${min[0]}) {
		return ${min[1]};
	} else if (xvalue >= ${max[0]}) {
		return ${max[1]};
	} else {
		struct lookup_entry_t low = get_lookup_entry(0);
		for (${idx_type} i = 1; i < ${len(points)}; i++) {
			struct lookup_entry_t high = get_lookup_entry(i);
			if ((xvalue >= low.x) && (xvalue < high.x)) {
				return interpolate(xvalue, &low, &high);
			}
			low = high;
		}
	}
	return 0;
}

#ifdef __TEST_LOOKUP_CODE__
/* gcc -std=c11 -Wall -O3 -D__TEST_LOOKUP_CODE__ -o ${filename} ${filename}.c && ./${filename} */

#include <stdio.h>

int main() {
	for (${extd_in_type} x = ${min[0]}; x < ${max[0]}; x++) {
		${out_type} y = ${lup_name}(x);
		printf("%5d -> %d\n", x, y);
	}
	return 0;
}
#endif
